
set(FILES
    Include/HCPEngine/HCPEngineBus.h
    Include/HCPEngine/HCPEngineTypeIds.h
    Source/HCPEngineSystemComponent.cpp
    Source/HCPEngineSystemComponent.h
    Source/HCPVocabulary.cpp
    Source/HCPVocabulary.h
    Source/HCPTokenizer.cpp
    Source/HCPTokenizer.h
    Source/HCPParticlePipeline.cpp
    Source/HCPParticlePipeline.h
    Source/HCPStorage.cpp
    Source/HCPStorage.h
    Source/HCPSocketServer.cpp
    Source/HCPSocketServer.h
    Source/HCPBondCompiler.cpp
    Source/HCPBondCompiler.h
    Source/HCPCacheMissResolver.cpp
    Source/HCPCacheMissResolver.h
    Source/HCPJsonInterpreter.cpp
    Source/HCPJsonInterpreter.h
    Source/HCPSuperpositionTrial.cpp
    Source/HCPSuperpositionTrial.h
    Source/HCPWordSuperpositionTrial.cpp
    Source/HCPWordSuperpositionTrial.h
    Source/HCPResolutionChamber.h
    Source/HCPVocabBed.cpp
    Source/HCPVocabBed.h
    Source/HCPEnvelopeManager.cpp
    Source/HCPEnvelopeManager.h
    Source/HCPEntityAnnotator.cpp
    Source/HCPEntityAnnotator.h
    Source/HCPDbConnection.cpp
    Source/HCPDbConnection.h
    Source/HCPDbUtils.h
    Source/HCPPbmWriter.cpp
    Source/HCPPbmWriter.h
    Source/HCPPbmReader.cpp
    Source/HCPPbmReader.h
    Source/HCPDocumentQuery.cpp
    Source/HCPDocumentQuery.h
    Source/HCPDocVarQuery.cpp
    Source/HCPDocVarQuery.h
    Source/HCPBondQuery.cpp
    Source/HCPBondQuery.h
    Source/HCPDatabaseBackend.h
    Source/HCPPostgresBackend.cpp
    Source/HCPSqliteBackend.cpp
)
